project_id = "hgyugpllpcbjvhumxeoj"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.admin-auth]
    verify_jwt = false
  [functions.admin-login]
    verify_jwt = false
  [functions.admin-session]
    verify_jwt = false
  [functions.admin-products]
    verify_jwt = false
  [functions.admin-upload]
    verify_jwt = false
