// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded publishable credentials (publishable/anon key — safe in client bundle)
// guarantee the production build can always reach the project even if VITE_ env
// vars don't make it into the deployment build step.
const FALLBACK_SUPABASE_URL = 'https://hgyugpllpcbjvhumxeoj.supabase.co';
const FALLBACK_SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhneXVncGxscGNianZodW14ZW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4NzY2MjcsImV4cCI6MjA4OTQ1MjYyN30.v3XicdCD2CZLRTlNOyB4lTLTEK2AnebsFdET9wiFrf4';

const ENV_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const ENV_SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();

const hasValidUrl = (value: string | undefined) => {
  if (!value) return false;
  try {
    const url = new URL(value);
    return url.protocol === 'https:' || url.protocol === 'http:';
  } catch {
    return false;
  }
};

const resolvedSupabaseUrl = hasValidUrl(ENV_SUPABASE_URL) ? ENV_SUPABASE_URL! : FALLBACK_SUPABASE_URL;
const resolvedSupabaseKey = ENV_SUPABASE_KEY || FALLBACK_SUPABASE_KEY;

// Always configured now thanks to baked-in publishable fallback.
export const isSupabaseConfigured = true;
export const SUPABASE_CONFIG_ERROR = '';

console.info("[supabase] client init", {
  envUrl: ENV_SUPABASE_URL ? "set" : "missing",
  envKey: ENV_SUPABASE_KEY ? "set" : "missing",
  using: ENV_SUPABASE_KEY ? "env" : "fallback",
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  resolvedSupabaseUrl,
  resolvedSupabaseKey,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
